version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kazyava33
      POSTGRES_DB: users_security
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data